apiVersion: v1
kind: Service
metadata:
  name: prediction-service
  namespace: w255
spec:
  selector:
    app: pythonapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer